language: go

# Set it up
install:
  - cd /tmp && curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.7.zip && unzip -q go_appengine_sdk_linux_amd64-1.9.7.zip
  - go get github.com/gorilla/mux

# run build
script: /tmp/go_appengine/goapp test $TRAVIS_BUILD_DIR/...

