language: go

# Set it up
install:
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.7.zip && unzip -q go_appengine_sdk_linux_amd64-1.9.7.zip

# run build
script: ./go_appengine/goapp build

