application: how-many-pullups
version: 1
runtime: go
api_version: go1

#default_expiration: "1h"

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /add
  script: _go_app
  login: admin

- url: /total
  script: _go_app

- url: /app
  static_dir: app

- url: /(.*)
  static_dir: app

- url: /(.*)
  static_files: app/index.html
  upload: app/(.*)

