application: how-many-pullups
version: 1
runtime: go
api_version: go1

#default_expiration: "1h"

handlers:

- url: /add
  script: _go_app
  login: admin

- url: /(total|export)
  script: _go_app

- url: /app
  static_dir: app

- url: /(.*)
  static_dir: app

- url: /(.*)
  static_files: app/index.html
  upload: app/(.*)

