application: how-many-pullups
version: 1
runtime: go
api_version: go1

#default_expiration: "1h"

handlers:
- url: /(admin|add)
  script: _go_app
  login: admin

- url: /hello
  script: _go_app
  login: required

- url: /.*
  script: _go_app
