application: how-many-pullups
version: 1
runtime: go
api_version: go1

#default_expiration: "1h"

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /(admin|add)
  script: _go_app
  login: admin

- url: /total
  script: _go_app

- url: /hello
  script: _go_app
  login: required

- url: /(.*)
  static_dir: html

- url: /(.*)
  static_files: html/index.html
  upload: html/(.*)

